# fly.toml app configuration file generated for overwatch-match-tracker on 2023-07-19T02:02:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "overwatch-match-tracker"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
    internal_port = 8081
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    processes = ["app"]

[mounts]
source = "litefs"
destination = "/data"
